import Image from 'next/image'
import React from 'react'

export const metadata = {
  title: 'Circular Economy',
  description: 'Circular Economy | SMC Sustainability',
}

export default function Index() {
  return (
    <section className='article-container'>
      <div className='block-content'>
        <article className='article'>
          <section className='description-container'>
            <h1>Circular Economy </h1>


            <p>The concept of circular economy has been
              part of our culture even before the term
              was mainstreamed. Since establishing a
              circular economy approach is part of our
              topmost sustainability goals, we recognize
              the importance of utilizing our resources
              sustainably, through better efficiency and the
              reduction of waste.</p>

            <p>We recognize that the Company consumes
              a large amount of both renewable and nonrenewable resources throughout its various
              business activities. With our continued
              push toward nation building, our demand
              for resources will inevitably increase as the
              Company grows. To address this, we aim to
              transform our business model and to “close the
              loop” in order to shrink our material footprint
              and to prevent any adverse impacts on the
              environment. We have adopted practices of
              reduction, recycling, and recovery, as well as
              developed programs and policies. We strive to
              become more efficient in the materials we use
              and reduce the amount of waste we generate.</p>

            <h3 className='green'>
              Materials and Waste
            </h3>

            <h5 className='brown'>Materials Management</h5>

            <Image style={{ borderRadius: '0' }} src="materials_management.png" width={436} height={201} alt='Materials Management' />

            <p>
              We used 15.7 million MT of materials in 2022
              for our operations. Of this, 65.7% are nonrenewable materials and the remaining 34.3%
              are renewable materials. Most material inputs
              were used by Petron and NCC in the form of
              crude oil, limestone, and clinker. We were able
              to recycle 442 thousand MT of the materials we
              used. These recycled items consisted mostly
              of glass bottles retrieved at post-consumer
              stage, for reuse by our beverage businesses, or
              broken glass cullets recycled by our packaging
              business. Also recycled are coal ash from SMGP’s
              power plants used as raw material in the cement
              production process of NCC. In 2022, NCC successfully
              recycled 150,194 MT of coal ash as inputs for cement.
            </p>

            <h3 className='green'>
              We have adopted practices
              of reduction, recycling,
              and recovery, as well as
              developed programs and
              policies. We strive to
              become more efficient
              in the materials we use
              and reduce the amount of
              waste we generate.
            </h3>

            <h5 className='brown'>Solid Waste Management </h5>

            <p>We understand the importance of proper waste
              management to our business operations. The
              Company already has ongoing initiatives designed
              to reduce the amount of waste we generate. We
              accomplish this by finding ways to recirculate byproducts and materials at their highest value.</p>

            <Image style={{ borderRadius: '0' }} src="solid_waste_diverted.png" width={435} height={198} alt='Solid Waste Management' />


            <p>The Company generated 330.6 thousand MT of solid
              waste in 2022, of which we were able to redirect
              approximately 90.3%. Waste classified as spent grain
              and spent yeast, generated by SMFB, has the largest
              contribution to our solid waste. Spent grain and
              spent yeast are protein-rich materials used by our
              animal feeds business, providing nutrients required
              by poultry and livestock for maintenance, growth, and
              reproduction. </p>

            <p>The second largest contributors were glass,
              cullets, and jars used for our bottles and
              beverages, which we were able to reuse or
              recycle. SMB has in place a returnable glass
              bottle system that encourages customers to
              return empty bottles, which the company then
              retrieves from retail outlets. On the other hand,
              GSMI has a robust bottle retrieval system
              through a network of territorial bottle suppliers.
              Recovered bottles are subjected to thorough
              inspection and quality control protocols to
              ensure safety for reuse. Both systems greatly
              reduce the need to manufacture new bottles,
              minimizing product cost and conserving
              material resources. </p>

            <p>Meanwhile, sludge and slop from wastewater
              treatment facilities, and manure from SMF’s
              poultry and pig farms are converted to organic
              fertilizer. Metal scraps, plastic waste and other
              non-hazardous waste that cannot be used in our
              operations are sold to recyclers. The remaining
              solid waste that could not be recycled is sent to
              landfills.</p>

            <p>The Company is prepared to be fully compliant
              with the Republic Act No. 11898, the Extended
              Producer Responsibility (EPR) Act of 2022,
              which became effective on August 13, 2022. The
              law requires obliged enterprises, such as SMFB,
              to recover and divert at least 20% of their 2022
              plastic packaging footprint by the end of 2023
              and increase this annually up to 80% by the end
              of 2028. In future reports, we will be providing
              information on their compliance with EPR.</p>

            <h5 className='brown'>Coal Ash Management </h5>

            <Image style={{ borderRadius: '0' }} src="coal_ash_management.png" width={440} height={196} alt='Coal Ash Management' />


            <p>We generated a total of 566.6 thousand MT
              of coal combustion residuals from our power
              generators. We were able to redirect a portion
              of the coal ash and reuse these in our cement
              manufacturing process. The CCR that were
              not reused in our cement plants were sent to
              external companies for further recycling. As
              a result, we were able to recycle 51.6% of our
              generated coal ash in 2022. </p>

            <h5 className='brown'>Hazardous Waste Management  </h5>

            <Image style={{ borderRadius: '0' }} src="hazardous_waste_management.png" width={437} height={196} alt='Hazardous Waste Management' />

            <p>The Company generated 8.9 thousand MT of
              hazardous waste in 2022. Our hazardous waste
              is mostly made up of used oil and sludge from
              our vehicles and generators, as well as reactive
              chemical waste from various manufacturing
              processes. We were able to divert 36.2% of our
              total hazardous waste generated.</p>

            <p>Hazardous waste is strictly regulated by
              environmental regulatory agencies. We abide by
              all laws and regulations regarding hazardous
              waste tracking, usage, and disposal. The
              Company has established a hazardous waste
              and solid waste management system that
              monitors the inventory, generation, and disposal
              of waste. Our Pollution Control Officers are
              tasked with data management and ensuring
              governmental compliance.</p>


            <Image src="TurninGasteintoResource.png" width={1150} height={700} alt='Hazardous Waste Management' />

            <h3 className='green'>Turning Waste into Resource</h3>

            <p>We make conscious and disciplined efforts to
              recycle coal combustion residuals (CCR), mainly as
              an aggregate material for cement manufacturing.
              We utilize coal ash as a supplementary material
              and as a substitute for clinker, an input used
              to strengthen cement. While coal ash cannot
              completely replace clinker in cement production,
              using it as an add-on contributes to reducing GHG
              emissions.</p>

            <p>SMGP’s Limay Power Plant and Malita Power Plant
              have been successful in recycling as much as
              80-90% and 70-80% of their coal ash, respectively.
              This is achieved through recycling coal ash from
              Limay Power Plant at Petron Bataan Refinery’s cogeneration facility, reducing the plants’
              consumption of virgin inert materials (e.g. silica
              sand), and supplying NCC and Southern Concrete
              with aggregate material for cement production.</p>

            <p>Since not all CCR can be recycled, we put
              significant efforts and investments in proper
              storage of the excess. We strictly follow and
              comply with the DENR’s Water Quality Guidelines
              and General Effluent Standard of 2016 (DAO 2016-
              08) to ensure proper management, storage, and
              monitoring. </p>

            <p>We also value the involvement of our partner
              communities. We carry out information, education,
              and communication campaigns to discuss specific
              measures undertaken to ensure that our activities
              do not cause harm to the environment and to the
              health of individuals.</p>

            <p>We also employ biomats made up of biodegradable
              natural fibers, such as straw, coir, and jute, to
              cover the ash and prevent erosion and blowing
              away. The biomats have seedlings already planted,
              which provide immediate soil stabilization and
              protection, and strengthen vegetation on slopes.
              This area will eventually be covered in trees by
              the end of its 25-year lifespan</p>


            <Image src="Byproduct.png" width={1150} height={1139} alt='From Byproduct to Benefit' />

            <h3 className='green'>From Byproduct to Benefit</h3>

            <p>As one of the largest manufacturing
              companies in the country, San Miguel
              Brewery (SMB) strives for excellence,
              efficiency, and sustainability. It places great
              emphasis on sustaining the integrity of its
              supply chain from sourcing to production
              to distribution, including managing its
              byproducts.</p>

            <p>One of the ways SMB keeps its byproducts in
              check is by developing a system that handles
              them responsibly—whether for disposal, reuse,
              or recycling. Solid waste, particularly wastewater
              sludge and spent grain, are some of the major
              byproducts of the beverage-making process.
              SMB’s commitment to circularity is evident as it
              has successfully recycled about 23 MT of these
              byproducts on a daily basis across its seven
              breweries nationwide. </p>

            <p>Wastewater sludge accumulates during the
              treatment of brewery effluents. These sedimentary
              materials are rich in organic matter making it
              suitable as sanitary landfill cover (to reduce landfillrelated emissions, fire hazard, and prevent blowing
              litter and dust) and as organic fertilizer. Spent
              grain, on the other hand, is the byproduct of raw
              materials that go through the brewing process. These
              are protein-rich materials used for hog feeds and
              other feed types, providing nutrients required for
              maintenance, growth, and reproduction.
            </p>

            <p>SMB’s production facilities handle the dewatered
              sludge by moving it to areas that can be transformed
              into fertile soil, which the company donates to
              various organizations in need.</p>

            <p>Polo Brewery, located in Valenzuela, has been
              donating its dewatered sludge to the local DENR
              office since 2018 to be used as effective landfill
              covers for specific areas in the city. </p>

            <p>Mandaue Brewery, located in Cebu, has partnered
              with the Department of Agriculture and the
              Metropolitan Cebu Water District in diverting its
              dewatered sludge as fertilizer. Most of the donations
              are channeled to nurseries that grow seedlings for
              various tree-planting activities also initiated by the
              brewery.
            </p>

            <p>Tagoloan Brewery, located in Misamis Oriental, also
              began donating its dewatered sludge to the Municipal
              Agriculture Office in 2021. The partnership has been
              yielding mutual benefits for both parties, albeit still in
              its pilot phase.</p>

            <p>The majority of SMB’s breweries divert their spent
              grain directly to B-MEG under San Miguel Foods, after
              they go through processing in SMB’s drying plants. </p>

            <p>B-MEG was SMC’s initial foray into the poultry and
              livestock industry and started from a one-ton feed
              mill adjacent to the brewery, growing into the marketleading feed brand in the Philippines today with
              close to 900 MT per hour rated capacity. It is thus
              fitting that, through the years, the feeds business has
              consistently utilized byproducts of beer production
              and, in doing so, absorbed a large volume of what
              would otherwise be waste materials and converted
              these into high-quality animal feeds. </p>

            <p>Due to rising demand for beer products, which results
              in an increase in production volume, some of SMB’s
              production facilities engage local organizations to
              divert their oversupply of spent grain for repurposing.
              These partnerships not only solve the oversupply
              concerns of the breweries but also aid the livelihood
              of local business owners by providing cost-efficient
              solutions to their business requirements. </p>

            <p>While Mandaue Brewery taps business partners to
              purchase its extra spent grain, Bacolod Brewery in
              Negros Occidental partners with local cattle raisers.
              Since 2017, Bacolod Brewery has partnered with
              the United Cattle Raisers Association in Negros and
              Visayas (UCRAIN-V) and the Negros First Ranch
              under the Negros Occidental Provincial Veterinary
              Office. The brewery provides free spent grain, which
              aids these organizations in providing their livestock
              with consistent nutritious feeds. </p>

            <p>“The addition of spent grains in the diet of our
              cattle has greatly improved the quality of our daily
              rations at no cost,” shares UCRAIN-V President Louis
              Martin. “It has drastically lessened our dependence
              on commercial feed inputs thus lowering our total
              feeding cost, especially during dry season when grass
              growth is low. We have seen a drastic improvement
              in the overall condition and performance of our
              breeders, increases in the daily gain in weight of our
              fatteners and in the milk production of our milkers.</p>

            <p>“The members of UCRAIN-V are aware that all these
              gains would not have happened without the spent
              grains from the brewery. We continue to hope and
              pray that this partnership will continue and grow
              in the future. This has also contributed to the food
              security program of our province.”
            </p>


            <Image src="Segregation_Bins .png" width={1150} height={700} alt='Segregation Bins' />

            <h3 className='green'>Closing the loop</h3>

            <p>Discarded glass containers and cullets are important raw materials in a bottle-to-bottle
              closed loop. Glass is 100% recyclable, nonporous, and impermeable, which means it
              can be perpetually recycled without any real loss of quality. However, despite this, the
              Philippines has only managed to recycle around 40% of its glass, lagging behind other
              countries like Spain, Belgium, and Switzerland, which have achieved recycling rates
              from 73% to as high as 90%.</p>

            <p>This is a challenge not only for the country but
              also for the packaging industry, a challenge which
              SMYPC has accepted through its long-standing
              and thriving practice of adopting a circular
              economy approach in its business model and
              operations. </p>

            <p>SMYPC engages with customers and key partners
              to return used glass containers for recycling. The
              bulk of its collected glass materials come from
              major beverage customers, as its supply contracts
              include the return of up to 100% of the customers’
              used glass containers. In 2022, two major
              customers turned over 100% of their used glass
              containers to SMYPC.</p>

            <p>Another initiative of SMYPC on circularity is the
              Balik Bote Program, which promotes the return of
              identified glass bottles and containers, including
              broken glass known as cullets, to SMYPC’s glass
              plants. </p>

            <p>In 2022, SMYPC intensified its support of the Balik
              Bote Program by launching an information and
              education campaign to encourage the mindset and
              behavior of segregating and cleaning at source
              or at the household level. This campaign was
              done in partnership with the local communities
              where SMYPC operates. Core programs were
              implemented in its own facilities, with major LGUs,
              and with participating schools.</p>

            <Image src="Turnover_of_donation_1.png" width={1150} height={700} alt='Turnover of Donations' />

            <p>Balik Bote with LGUs began in July 2022
              with one of the major cities in Metro Manila.
              SMYPC partnered with a waste management
              solutions organization to expand the city’s waste
              management program by adding glass to their
              recoverable and recyclable materials portfolio.
              SMYPC also initiated an information campaign to
              instill the discipline of segregating and cleaning
              at the household level. Through this, SMYPC
              was able to significantly increase awareness on
              the recyclability of glass and expand its area of
              coverage by setting up collection sites in LGUs
              within the NCR. </p>

            <Image src="smc_packaging_corp.png" width={1150} height={610} alt='SMC Packaging Team' />

            <p>
              SMYPC also spearheaded the Balik Bote Program
              in its own facilities. With the program already
              deeply integrated into the culture of SMY Glass
              Plant where it has been implemented for decades,
              the program was expanded to other non-glass
              manufacturing facilities of SMYPC in Cavite and
              Laguna, as well as to communities and public
              schools near their areas of operation.
            </p>

            <Image src="Turnover_of_donation_2.png" width={1150} height={821} alt='Turnover of Donations' />

            <p>
              To encourage participation from these
              communities and schools, SMYPC provides
              an incentive in the form of school and office
              equipment and supplies, based on a proportionate
              amount of recyclables collected throughout the
              year. This has resulted in a combined collection
              volume of 34 MT in 2022, a 52% increase from the
              previous year in 2021.
            </p>

            <p>To date, SMYPC has recovered a total of 137,000
              MT of discarded glass containers through its
              circular initiatives in 2022, and it continues to
              work with partner communities and stakeholders
              to further increase used bottle collection and bring
              the Philippines on par with leading countries in
              glass recycling.</p>



            <Image src="glass_bottles.png" width={1150} height={767} alt='GLASS BOTTLES' />
            <h3 className='green'> <small>GLASS BOTTLES</small> <br />
              Where it all began</h3>

            <p>Long before sustainability and circular
              economy practices became bywords in
              modern business, San Miguel Brewery,
              one of the country’s oldest enterprises
              and Southeast Asia’s first brewer, was
              already employing its returnable glass
              bottle (RGB) system, which endures as a
              critical part of its business. </p>

            <p>For many decades, SMB’s RGB system has
              contributed significantly to its bottom line,
              minimizing costs and reducing required resources
              through the constant reuse and recycling of glass
              bottles. Under the system, customers only pay for
              the contents and a deposit on the bottle when they
              buy products. Returning the bottles to recover
              the deposit becomes nearly routine for customers
              nationwide, allowing the bottles to be brought
              back to the SMB system where these are washed,
              sanitized, and reused.</p>

            <p>SMB’s glass bottles are designed to go through
              this cycle 60 times or more. SMB ensures that
              recycled bottles follow the company’s strict
              quality standards, which also consider the bottles’
              aesthetic value. Visibly worn bottles are sent to
              SMB’s sister company, SMYPC, for recycling, along
              with bottles reaching their end-of-life stage. This
              ensures that all bottles are recycled, and none are
              wasted.</p>

            <Image src="glass_bottles_2.png" width={1150} height={767} alt='GLASS BOTTLES 2' />

            <p>As glass is perpetually 100% recyclable, the
              system, in place for most of the company’s 132-
              year history, has afforded both SMB and the
              environment incalculable benefits in lower costs,
              decreased extraction of new raw materials and
              minimized solid waste in landfills. This has also
              helped to ingrain a zero-waste mindset in our
              culture. </p>

            <p>In many ways, glass bottle retrieval and recycling
              is also crucial for SMC’s spirits business, Ginebra
              San Miguel Inc. The preference for glass bottles
              as packaging material stems from its inherent
              characteristic to preserve the quality of our
              products for a longer period of time as well as its
              high reusability and recyclability. </p>

            <p>With an expansive network of third-party bottle
              suppliers that spans the whole Philippine
              archipelago, used bottles are retrieved, sorted and
              pre-washed prior to delivery at GSMI’s various
              bottling facilities. Upon acceptance, these bottles
              undergo stringent quality inspections and further
              cleaning prior to filling with Ginebra’s products.
              Bottles deemed unfit for reuse are transformed
              into glass cullet, which are then sold to SMYPC to
              be recycled into new bottles once again.</p>

            <p>This highly efficient system of retrieval and reuse
              keeps GSMI’s bottle in circulation for as long as
              possible to effectively reduce its requirement
              for brand new bottles by 72% in 2022. But more
              importantly, aside from minimizing production
              costs, it helps prevents the accumulation of solid
              waste and reduces the use of natural resources
              needed to produce new bottles. This program
              not only supports cost management for the
              company but also plays a crucial role in reducing
              glass bottle manufacturers’ dependence on new
              materials, leading to a substantial positive impact
              on the environment.</p>

            <p>Furthermore, both SMB and GSMI also maintain
              their own internal bottle retrieval programs to
              encourage employees to contribute to the effort to
              minimize the number of uncollected bottles not in
              their systems.
            </p>

            <p>SMYPC plays a crucial role in the success of both
              SMB’s and GSMI’s circular economy programs.
              With its business model for discarded glass
              containers and cullets, SMYPC’s raw materials,
              fuel, power consumption, and waste generation
              are significantly reduced.</p>


            <Image src="pallet_1.png" width={1150} height={644} alt=' From  pallet to planet' />
            <h3 className='green'>From  pallet to planet</h3>

            <p>Manila Plastics Plant (MPP) is one of
              the domestic manufacturing facilities
              of SMYPC. It manufactures durable and
              economical rigid plastic products such as
              crates, pallets, food trays, bottles, pails,
              and plastic flooring. With plastic being
              non-biodegradable, the business has
              found ways to reduce its impact on the
              environment through the adaptation of a
              circular economy model. </p>

            <Image src="pallet_2.png" width={280} height={333} alt=' From  pallet to planet' />


            <p>MPP has several programs for recycling
              collected condemned plastic products, such as
              the Pallet to Pallet and Crate for Crate (P2P
              and C4C) initiatives, wherein the business
              recovers damaged pallets and crates from its
              customers and recycles them into new pallets
              or crates. A similar process is implemented with
              post-consumer lube oil plastic bottles. Aside
              from minimizing plastic waste, these programs
              strengthen the relationship between MPP
              and its customers through a shared program
              for sustainability. </p>

            <p>For 2022, MPP utilized 4,148 MT of recycled
              materials for the creation of new plastic
              packaging, resulting in an equivalent reduction in
              virgin material for production.</p>

          </section>
        </article>
      </div>
    </section>
  )
}
